-- Question 4: Hospital Management Package with Bulk Processing
-- Create tables for patients and doctors

CREATE TABLE patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name VARCHAR2(100) NOT NULL,
    age NUMBER(3),
    gender VARCHAR2(10) CHECK (gender IN ('Male', 'Female', 'Other')),
    admitted_status VARCHAR2(20) DEFAULT 'Not Admitted' CHECK (admitted_status IN ('Admitted', 'Not Admitted', 'Discharged')),
    admission_date DATE,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE doctors (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_name VARCHAR2(100) NOT NULL,
    specialty VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMIT;

-- Add sample doctors
INSERT INTO doctors (doctor_name, specialty) VALUES ('Dr. Smith', 'Cardiology');
INSERT INTO doctors (doctor_name, specialty) VALUES ('Dr. Johnson', 'Neurology');
INSERT INTO doctors (doctor_name, specialty) VALUES ('Dr. Williams', 'Pediatrics');
INSERT INTO doctors (doctor_name, specialty) VALUES ('Dr. Brown', 'Orthopedics');
INSERT INTO doctors (doctor_name, specialty) VALUES ('Dr. Davis', 'Emergency Medicine');

COMMIT;

-- Package specification
CREATE OR REPLACE PACKAGE hospital_mgmt_pkg IS
    
    -- Collection types for bulk operations
    TYPE patient_record_type IS RECORD (
        patient_name VARCHAR2(100),
        age NUMBER(3),
        gender VARCHAR2(10),
        admitted_status VARCHAR2(20)
    );
    
    TYPE patient_collection_type IS TABLE OF patient_record_type;
    
    -- Cursor for patient data
    TYPE patient_cursor_type IS REF CURSOR RETURN patients%ROWTYPE;
    
    -- Bulk insert patients
    PROCEDURE bulk_load_patients(p_patients IN patient_collection_type);
    
    -- Get all patients
    FUNCTION show_all_patients RETURN patient_cursor_type;
    
    -- Count admitted patients
    FUNCTION count_admitted RETURN NUMBER;
    
    -- Admit a patient
    PROCEDURE admit_patient(p_patient_id IN NUMBER);
    
    -- Other useful functions
    PROCEDURE discharge_patient(p_patient_id IN NUMBER);
    
    FUNCTION get_patient_info(p_patient_id IN NUMBER) RETURN patients%ROWTYPE;
    
    -- Filter patients by status
    FUNCTION get_patients_by_status(p_status IN VARCHAR2) RETURN patient_cursor_type;

END hospital_mgmt_pkg;
/

-- Package body
CREATE OR REPLACE PACKAGE BODY hospital_mgmt_pkg IS

    -- Bulk insert multiple patients at once
    PROCEDURE bulk_load_patients(p_patients IN patient_collection_type) IS
        v_names     DBMS_SQL.VARCHAR2_TABLE;
        v_ages      DBMS_SQL.NUMBER_TABLE;
        v_genders   DBMS_SQL.VARCHAR2_TABLE;
        v_statuses  DBMS_SQL.VARCHAR2_TABLE;
    BEGIN
        IF p_patients IS NULL OR p_patients.COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'No patient data provided for bulk loading');
        END IF;
        
        -- Set up data for bulk insert
        FOR i IN p_patients.FIRST .. p_patients.LAST LOOP
            v_names(i) := p_patients(i).patient_name;
            v_ages(i) := p_patients(i).age;
            v_genders(i) := p_patients(i).gender;
            v_statuses(i) := NVL(p_patients(i).admitted_status, 'Not Admitted');
        END LOOP;
        
        -- Insert all records at once
        FORALL i IN v_names.FIRST .. v_names.LAST
            INSERT INTO patients (patient_name, age, gender, admitted_status)
            VALUES (v_names(i), v_ages(i), v_genders(i), v_statuses(i));
        
        COMMIT;
        
        DBMS_OUTPUT.PUT_LINE('Successfully loaded ' || p_patients.COUNT || ' patient records');
        
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20002, 'Error in bulk_load_patients: ' || SQLERRM);
    END bulk_load_patients;
    
    -- Get all patients as cursor
    FUNCTION show_all_patients RETURN patient_cursor_type IS
        v_cursor patient_cursor_type;
    BEGIN
        OPEN v_cursor FOR
            SELECT patient_id, patient_name, age, gender, admitted_status, admission_date, created_at
            FROM patients
            ORDER BY patient_id;
        
        RETURN v_cursor;
    END show_all_patients;
    
    -- Count how many patients are admitted
    FUNCTION count_admitted RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM patients
        WHERE admitted_status = 'Admitted';
        
        RETURN v_count;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END count_admitted;
    
    -- Change patient status to admitted
    PROCEDURE admit_patient(p_patient_id IN NUMBER) IS
        v_current_status VARCHAR2(20);
        v_patient_name VARCHAR2(100);
    BEGIN
        -- Check if patient exists and get current status
        BEGIN
            SELECT admitted_status, patient_name
            INTO v_current_status, v_patient_name
            FROM patients
            WHERE patient_id = p_patient_id;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20003, 'Patient ID ' || p_patient_id || ' not found');
        END;
        
        -- Don't admit if already admitted
        IF v_current_status = 'Admitted' THEN
            RAISE_APPLICATION_ERROR(-20004, 'Patient ' || v_patient_name || ' is already admitted');
        END IF;
        
        -- Set patient as admitted
        UPDATE patients
        SET admitted_status = 'Admitted',
            admission_date = SYSDATE
        WHERE patient_id = p_patient_id;
        
        COMMIT;
        
        DBMS_OUTPUT.PUT_LINE('Patient ' || v_patient_name || ' (ID: ' || p_patient_id || ') has been admitted');
        
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END admit_patient;
    
    -- Discharge a patient
    PROCEDURE discharge_patient(p_patient_id IN NUMBER) IS
        v_current_status VARCHAR2(20);
        v_patient_name VARCHAR2(100);
    BEGIN
        -- Check if patient exists and get current status
        BEGIN
            SELECT admitted_status, patient_name
            INTO v_current_status, v_patient_name
            FROM patients
            WHERE patient_id = p_patient_id;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20005, 'Patient ID ' || p_patient_id || ' not found');
        END;
        
        -- Check if patient is currently admitted
        IF v_current_status != 'Admitted' THEN
            RAISE_APPLICATION_ERROR(-20006, 'Patient ' || v_patient_name || ' is not currently admitted');
        END IF;
        
        -- Set patient as discharged
        UPDATE patients
        SET admitted_status = 'Discharged'
        WHERE patient_id = p_patient_id;
        
        COMMIT;
        
        DBMS_OUTPUT.PUT_LINE('Patient ' || v_patient_name || ' (ID: ' || p_patient_id || ') has been discharged');
        
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END discharge_patient;
    
    -- Get patient details
    FUNCTION get_patient_info(p_patient_id IN NUMBER) RETURN patients%ROWTYPE IS
        v_patient patients%ROWTYPE;
    BEGIN
        SELECT *
        INTO v_patient
        FROM patients
        WHERE patient_id = p_patient_id;
        
        RETURN v_patient;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20007, 'Patient ID ' || p_patient_id || ' not found');
        WHEN OTHERS THEN
            RAISE;
    END get_patient_info;
    
    -- Function to get patients by admission status
    FUNCTION get_patients_by_status(p_status IN VARCHAR2) RETURN patient_cursor_type IS
        v_cursor patient_cursor_type;
    BEGIN
        OPEN v_cursor FOR
            SELECT patient_id, patient_name, age, gender, admitted_status, admission_date, created_at
            FROM patients
            WHERE admitted_status = p_status
            ORDER BY patient_name;
        
        RETURN v_cursor;
    END get_patients_by_status;

END hospital_mgmt_pkg;
/

-- TEST SCRIPTS

-- Test 1: Bulk Load Patients
DECLARE
    v_patients hospital_mgmt_pkg.patient_collection_type;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 1: BULK LOAD PATIENTS ===');
    
    v_patients := hospital_mgmt_pkg.patient_collection_type();
    
    -- Add multiple patient records
    v_patients.EXTEND(5);
    v_patients(1).patient_name := 'John Smith';
    v_patients(1).age := 45;
    v_patients(1).gender := 'Male';
    v_patients(1).admitted_status := 'Not Admitted';
    
    v_patients(2).patient_name := 'Mary Johnson';
    v_patients(2).age := 32;
    v_patients(2).gender := 'Female';
    v_patients(2).admitted_status := 'Not Admitted';
    
    v_patients(3).patient_name := 'Robert Wilson';
    v_patients(3).age := 67;
    v_patients(3).gender := 'Male';
    v_patients(3).admitted_status := 'Not Admitted';
    
    v_patients(4).patient_name := 'Sarah Davis';
    v_patients(4).age := 28;
    v_patients(4).gender := 'Female';
    v_patients(4).admitted_status := 'Not Admitted';
    
    v_patients(5).patient_name := 'Michael Brown';
    v_patients(5).age := 55;
    v_patients(5).gender := 'Male';
    v_patients(5).admitted_status := 'Not Admitted';
    
    -- Bulk load patients
    hospital_mgmt_pkg.bulk_load_patients(v_patients);
    
    DBMS_OUTPUT.PUT_LINE('Test 1 completed successfully');
END;
/

-- Test 2: Display All Patients
DECLARE
    v_cursor hospital_mgmt_pkg.patient_cursor_type;
    v_patient patients%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 2: DISPLAY ALL PATIENTS ===');
    
    v_cursor := hospital_mgmt_pkg.show_all_patients;
    
    DBMS_OUTPUT.PUT_LINE('ID | Name | Age | Gender | Status | Admission Date');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
    
    LOOP
        FETCH v_cursor INTO v_patient;
        EXIT WHEN v_cursor%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(
            v_patient.patient_id || ' | ' ||
            v_patient.patient_name || ' | ' ||
            v_patient.age || ' | ' ||
            v_patient.gender || ' | ' ||
            v_patient.admitted_status || ' | ' ||
            NVL(TO_CHAR(v_patient.admission_date, 'DD-MON-YYYY'), 'N/A')
        );
    END LOOP;
    
    CLOSE v_cursor;
    DBMS_OUTPUT.PUT_LINE('Test 2 completed successfully');
END;
/

-- Test 3: Count Admitted Patients (before admissions)
DECLARE
    v_count NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 3: COUNT ADMITTED PATIENTS (BEFORE ADMISSIONS) ===');
    
    v_count := hospital_mgmt_pkg.count_admitted;
    DBMS_OUTPUT.PUT_LINE('Number of currently admitted patients: ' || v_count);
    
    DBMS_OUTPUT.PUT_LINE('Test 3 completed successfully');
END;
/

-- Test 4: Admit Patients
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 4: ADMIT PATIENTS ===');
    
    -- Admit first three patients
    hospital_mgmt_pkg.admit_patient(1);
    hospital_mgmt_pkg.admit_patient(2);
    hospital_mgmt_pkg.admit_patient(3);
    
    DBMS_OUTPUT.PUT_LINE('Test 4 completed successfully');
END;
/

-- Test 5: Count Admitted Patients (after admissions)
DECLARE
    v_count NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 5: COUNT ADMITTED PATIENTS (AFTER ADMISSIONS) ===');
    
    v_count := hospital_mgmt_pkg.count_admitted;
    DBMS_OUTPUT.PUT_LINE('Number of currently admitted patients: ' || v_count);
    
    DBMS_OUTPUT.PUT_LINE('Test 5 completed successfully');
END;
/

-- Test 6: Display Admitted Patients Only
DECLARE
    v_cursor hospital_mgmt_pkg.patient_cursor_type;
    v_patient patients%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 6: DISPLAY ADMITTED PATIENTS ONLY ===');
    
    v_cursor := hospital_mgmt_pkg.get_patients_by_status('Admitted');
    
    DBMS_OUTPUT.PUT_LINE('Admitted Patients:');
    DBMS_OUTPUT.PUT_LINE('ID | Name | Age | Gender | Admission Date');
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------');
    
    LOOP
        FETCH v_cursor INTO v_patient;
        EXIT WHEN v_cursor%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(
            v_patient.patient_id || ' | ' ||
            v_patient.patient_name || ' | ' ||
            v_patient.age || ' | ' ||
            v_patient.gender || ' | ' ||
            TO_CHAR(v_patient.admission_date, 'DD-MON-YYYY HH24:MI')
        );
    END LOOP;
    
    CLOSE v_cursor;
    DBMS_OUTPUT.PUT_LINE('Test 6 completed successfully');
END;
/

-- Test 7: Try to admit an already admitted patient (should raise error)
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 7: TRY TO ADMIT ALREADY ADMITTED PATIENT ===');
    
    BEGIN
        hospital_mgmt_pkg.admit_patient(1); -- Patient 1 is already admitted
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Expected error caught: ' || SQLERRM);
    END;
    
    DBMS_OUTPUT.PUT_LINE('Test 7 completed successfully');
END;
/

-- Test 8: Discharge a patient and verify count
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TEST 8: DISCHARGE PATIENT ===');
    
    hospital_mgmt_pkg.discharge_patient(1);
    
    DECLARE
        v_count NUMBER;
    BEGIN
        v_count := hospital_mgmt_pkg.count_admitted;
        DBMS_OUTPUT.PUT_LINE('Number of currently admitted patients after discharge: ' || v_count);
    END;
    
    DBMS_OUTPUT.PUT_LINE('Test 8 completed successfully');
END;
/

-- Final verification query
SELECT 
    patient_id,
    patient_name,
    age,
    gender,
    admitted_status,
    TO_CHAR(admission_date, 'DD-MON-YYYY HH24:MI:SS') AS admission_date
FROM patients
ORDER BY patient_id;

-- Summary statistics
SELECT 
    admitted_status,
    COUNT(*) as patient_count
FROM patients
GROUP BY admitted_status
ORDER BY admitted_status;